language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# php compatibility
php:
  - "7.2"
  - "7.3"

cache:
  - directories:
    - $HOME/.composer

before_script:
  - travis_retry composer install --no-interaction --prefer-dist
  - phpenv config-rm xdebug.ini
  - travis_retry composer upgrade --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/php-cs-fixer fix --dry-run --verbose
  - vendor/bin/php-cs-fixer fix --verbose
  - vendor/bin/phpcbf --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose
  - vendor/bin/phpstan.phar analyse --no-progress --level max src/ tests/

notifications:
  email: false
